In [15]:
import pandas as pd

viv_x_mzas = pd.read_csv("/tmp/pilar_vivs_x_mnza.csv")
print(viv_x_mzas)

viv_x_lado = pd.read_csv("/tmp/pilar_vivs_x_lado.csv")
print(viv_x_lado)

mzas_ady = pd.read_csv("/tmp/pilar_mzas_adyacentes.csv", dtype={'mza': object, 'mza_ady': object})
print(mzas_ady)

lados_ady = pd.read_csv("/tmp/pilar_lados_adyacentes.csv"
                        , dtype={'mza': object, 'd_lado': object, 'v_mza': object, 'v_lado': object, 'c_mza': object, 'c_lado': object})
print(lados_ady)

      depto  frac  radio manzana  viviendas
0       638     1      1     001         10
1       638     1      1     003         20
2       638     1      1     004          6
3       638     1      1     005          1
4       638     1      1     006          2
5       638     1      1     007          2
6       638     1      1     008          5
7       638     1      1     009          7
8       638     1      1      01          2
9       638     1      1     010          8
10      638     1      1     011          5
11      638     1      1     012          2
12      638     1      1     013          5
13      638     1      1      03          2
14      638     1      2       0          8
15      638     1      2     002          1
16      638     1      2     003         25
17      638     1      2     004         12
18      638     1      2     005         10
19      638     1      2     007         12
20      638     1      2     008         16
21      638     1      2     009         20
22      638     1      2     010         15
23      638     1      2     011         16
24      638     1      2     012          1
25      638     1      2     013         14
26      638     1      2     014         15
27      638     1      2     015         14
28      638     1      2     016         20
29      638     1      2     017         26
...     ...   ...    ...     ...        ...
7245    638    23      5     014          1
7246    638    23      5     015          1
7247    638    23      5     016          1
7248    638    23      5     017          1
7249    638    23      5     019          1
7250    638    23      6       0          1
7251    638    23      6     001          1
7252    638    23      6     002          2
7253    638    23      6     006         23
7254    638    23      6     007          6
7255    638    23      6     011          3
7256    638    23      7       0         17
7257    638    23      7     001          1
7258    638    23      7     002          1
7259    638    23      7     003          1
7260    638    23      7     004          1
7261    638    23      7     005         12
7262    638    23      7     006          4
7263    638    23      7     008          1
7264    638    23      7     009          1
7265    638    23      7     012          2
7266    638    23      7     014          4
7267    638    23      7     015          1
7268    638    23      7     016          1
7269    638    23      7     019          1
7270    638    23      7     022          1
7271    638    23      7     023          2
7272    638    23      7     025          1
7273    638    23      7     029          3
7274    638    23      7     032         19

[7275 rows x 5 columns]
       frac  radio  mza  lado  viviendas
0         1      1    1   3.0          4
1         1      1    1   NaN          4
2         1      1    1   NaN         16
3         1      1    3   3.0         33
4         1      1    3   NaN          6
5         1      1    3   NaN         27
6         1      1    4   NaN         78
7         1      1    5   NaN          1
8         1      1    6   NaN          4
9         1      1    7   NaN          6
10        1      1    8   2.0          6
11        1      1    8   4.0          9
12        1      1    9   4.0          6
13        1      1    9   NaN          8
14        1      1   10   2.0          6
15        1      1   10   NaN         10
16        1      1   11   NaN         10
17        1      1   12   7.0          8
18        1      1   13   1.0         12
19        1      1   13   NaN          8
20        1      2    2   NaN          2
21        1      2    3   1.0          7
22        1      2    3   2.0          4
23        1      2    3   3.0          9
24        1      2    3   5.0          5
25        1      2    4   1.0         16
26        1      2    4   3.0          8
27        1      2    5   1.0          4
28        1      2    5   2.0          4
29        1      2    5   NaN          2
...     ...    ...  ...   ...        ...
17448    23      5   15   NaN          2
17449    23      5   16   NaN          3
17450    23      5   17   NaN          2
17451    23      5   19   NaN          4
17452    23      6    1   NaN          3
17453    23      6    2   NaN          6
17454    23      6    6   NaN         92
17455    23      6    7   NaN         36
17456    23      6   11   3.0          3
17457    23      6   11   NaN          6
17458    23      7    1  95.0          8
17459    23      7    2   2.0          1
17460    23      7    3   NaN          4
17461    23      7    4   NaN          2
17462    23      7    5   4.0         21
17463    23      7    5   NaN         15
17464    23      7    6   4.0          6
17465    23      7    6   NaN          6
17466    23      7    8   NaN          5
17467    23      7    9   NaN          2
17468    23      7   12   NaN          6
17469    23      7   14   4.0          8
17470    23      7   15   1.0          7
17471    23      7   16   NaN          4
17472    23      7   19   NaN          2
17473    23      7   22   NaN          3
17474    23      7   23   NaN          2
17475    23      7   25   NaN          4
17476    23      7   29   NaN          9
17477    23      7   32  95.0         57

[17478 rows x 5 columns]
                mza       mza_ady
0      066380101001  066380101002
1      066380101001  066380101003
2      066380101002  066380101001
3      066380101002  066380101003
4      066380101002  066380101004
5      066380101002  066380101005
6      066380101002  066380101006
7      066380101002  066380101007
8      066380101002  066380101011
9      066380101003  066380101001
10     066380101003  066380101002
11     066380101003  066380101013
12     066380101004  066380101002
13     066380101004  066380101005
14     066380101004  066380101006
15     066380101004  066380101007
16     066380101004  066380101008
17     066380101004  066380101009
18     066380101004  066380101010
19     066380101004  066380101012
20     066380101005  066380101002
21     066380101005  066380101004
22     066380101005  066380101006
23     066380101006  066380101002
24     066380101006  066380101004
25     066380101006  066380101005
26     066380101006  066380101007
27     066380101007  066380101002
28     066380101007  066380101004
29     066380101007  066380101006
...             ...           ...
24502  066382307026  066382307025
24503  066382307026  066382307027
24504  066382307026  066382307028
24505  066382307027  066382307012
24506  066382307027  066382307026
24507  066382307028  066382307007
24508  066382307028  066382307013
24509  066382307028  066382307025
24510  066382307028  066382307026
24511  066382307028  066382307030
24512  066382307029  066382307002
24513  066382307029  066382307003
24514  066382307029  066382307009
24515  066382307029  066382307014
24516  066382307030  066382307007
24517  066382307030  066382307012
24518  066382307030  066382307019
24519  066382307030  066382307020
24520  066382307030  066382307021
24521  066382307030  066382307022
24522  066382307030  066382307023
24523  066382307030  066382307024
24524  066382307030  066382307025
24525  066382307030  066382307028
24526  066382307031  066382307001
24527  066382307031  066382307003
24528  066382307031  066382307004
24529  066382307031  066382307005
24530  066382307031  066382307006
24531  066382307032  066382307001

[24532 rows x 2 columns]
                mza  lado d_lado         v_mza v_lado         c_mza c_lado
0      066382101015     4      1  066382101016      2  066382101013      4
1      066382101015     4      1  066382101016      2  066382101014      4
2      066382102010     3      4  066382102017      1  066382102005      3
3      066381606003     1      2  066381606900      1  066381606899      1
4      066381606003     1      2  066381606901      1  066381606899      1
5      066380709014     2      3  066380709019      4           NaN    NaN
6      066381204042     3      1           NaN    NaN  066381204045      1
7      066380913018     4      1  066380913013      2  066380913017      4
8      066380105060     1      2  066380105057      3  066380105058      1
9      066381904038     3      1           NaN    NaN  066381904039      1
10     066381804002     3      4  066381804001      6           NaN    NaN
11     066381503010     4      1  066381503009      2  066381503011      4
12     066382001013     4      1  066382001012      4  066382001012      4
13     066380106014     2      3  066380106020      4  066380106021      2
14     066382002048     5      6           NaN    NaN           NaN    NaN
15     066381607014     4      1  066381607009      2  066381607015      4
16     066381607014     4      1  066381607009      2  066381607017      4
17     066381607014     4      1  066381607009      2  066381607016      4
18     066380906005     3      4           NaN    NaN           NaN    NaN
19     066381109019     3      1  066381109020      1  066381109018      1
20     066381010006     3      4  066381010007      1  066381010005      3
21     066380910010     3      4  066380910011      1  066380910007      3
22     066380614016     1      2  066380614017      3  066380614018      1
23     066382008010     2      3  066382008015      4  066382008013      2
24     066382002037     8      1  066382002036      2  066382002039      4
25     066382002037     8      1  066382002036      2  066382002040      4
26     066382002037     8      1  066382002036      2  066382002038      4
27     066381407020     2      3  066381407023      4           NaN    NaN
28     066381303016     4      1  066381303015      2  066381303015      3
29     066380406018     1      2           NaN    NaN           NaN    NaN
...             ...   ...    ...           ...    ...           ...    ...
33714  066381903017     2    NaN  066381903020      4           NaN    NaN
33715  066381903017     2    NaN  066381903021      4           NaN    NaN
33716  066381903017     2    NaN  066381903018      4           NaN    NaN
33717  066381802019     3    NaN  066381802020      1           NaN    NaN
33718  066380203010     1    NaN  066380203014      4           NaN    NaN
33719  066382003039     2    NaN  066382003040      4           NaN    NaN
33720  066382003039     2    NaN  066382003040      5           NaN    NaN
33721  066381806002     2    NaN  066381806013      4           NaN    NaN
33722  066380505022     3    NaN  066380505023      1           NaN    NaN
33723  066380401002     2    NaN  066380401003      4           NaN    NaN
33724  066380507009     1    NaN  066380507011      3           NaN    NaN
33725  066380912008     1    NaN  066380912007      3           NaN    NaN
33726  066380309035     2    NaN  066380309030      4           NaN    NaN
33727  066381507004     3    NaN  066381507003      1           NaN    NaN
33728  066380813013     4    NaN  066380813012      2           NaN    NaN
33729  066380706001     4    NaN  066380706018      2           NaN    NaN
33730  066381903029     1    NaN  066381903032      3           NaN    NaN
33731  066381305999     1    NaN  066381305002      3           NaN    NaN
33732  066381107022     2    NaN  066381107021      4           NaN    NaN
33733  066381106017     1    NaN  066381106018      3           NaN    NaN
33734  066380906017     4    NaN  066380906010      2           NaN    NaN
33735  066381704021     2    NaN  066381704024      1           NaN    NaN
33736  066381704021     2    NaN  066381704022      1           NaN    NaN
33737  066382002060     5    NaN  066382002048     95           NaN    NaN
33738  066382002060     5    NaN  066382002048      1           NaN    NaN
33739  066380902018     4    NaN  066380902017      2           NaN    NaN
33740  066380816001     2    NaN  066380816002      1           NaN    NaN
33741  066381901004     2    NaN  066381901003      4           NaN    NaN
33742  066380913003     1    NaN  066380913004      3           NaN    NaN
33743  066380310009     3    NaN  066380310010      3           NaN    NaN

[33744 rows x 7 columns]

In [1]:
import psycopg2
import pandas as pd

conn = psycopg2.connect(database = "halpe", user = "halpe", password = "halpe", host = "172.26.67.239", port = "5432")
print "Opened database successfully"

cur = conn.cursor()
sql = ("select frac, radio, ccalle::integer, ncalle, hnpuerta, hpiso, mza::integer, lado, seg, count(*) "
    "from prueba_piloto.pilar "
    "where (frac, radio, mza) in ( "
        "select frac, radio, mza "
        "from prueba_piloto.pilar "
        "where prueba_piloto.isnumeric(mza) and mza::integer != 0 "
        "group by frac, radio, mza "
        "having count(*) between 60 and 40 "
        "or count(*) > 90) "
    "group by frac, radio, ccalle::integer, ncalle, hnpuerta, hpiso, mza::integer, lado, seg "
    "order by frac, radio, mza::integer, seg, ccalle, hnpuerta"
    )
cur.execute(sql)
colnames = [desc[0] for desc in cur.description]
df = pd.DataFrame(cur.fetchall(), columns = colnames)


print(df)

print "Operation done successfully";
conn.close()

Opened database successfully
     frac radio  ccalle            ncalle hnpuerta hpiso  mza  lado seg  count
0      01    11       0            DURANO    01102     0    1  None  01      1
1      01    11       0           FIORINI    01719     0    1  None  01      1
2      01    11       0           FIORINI    01731     0    1  None  01      1
3      01    11       0           FIORINI    01743     0    1  None  01      1
4      01    11       0            DURAND    01744     0    1  None  01      1
5      01    11       0            DURAND    01756     0    1  None  01      2
6      01    11       0            DURAND    01782     0    1  None  01      2
7      01    11       0             GAITO    01794     0    1  None  01      1
8      01    11       0             GAITO    02226     0    1  None  01      1
9      01    11       0             GAITO    02236     0    1  None  01      1
10     01    11       0          CALCAGNO    02237     0    1  None  01      1
11     01    11       0          CALGAGNO    02245     0    1  None  01      1
12     01    11       0          CALCAGNO    02273     0    1  None  01      1
13     01    11       0                 0    00481     0    1  None  04      1
14     01    11       0                 0    00482     0    1  None  04      1
15     01    11       0                 0    00483     0    1  None  04      1
16     01    11       0                 0    00484     0    1  None  04      1
17     01    11       0                 0    00485     0    1  None  04      1
18     01    11       0                 0    00486     0    1  None  04      1
19     01    11       0                 0    00487     0    1  None  04      1
20     01    11       0                 0    00488     0    1  None  04      1
21     01    11       0                 0    00489     0    1  None  04      1
22     01    11       0                 0    00490     0    1  None  04      1
23     01    11       0                 0    00491     0    1  None  04      1
24     01    11       0                 0    00492     0    1  None  04      1
25     01    11       0                 0    00493     0    1  None  04      1
26     01    11       0                 0    00497     0    1  None  04      1
27     01    11       0                 0    00499     0    1  None  04      1
28     01    11       0                 0    00430     0    1  None  05      1
29     01    11       0                 0    00460     0    1  None  05      1
...   ...   ...     ...               ...      ...   ...  ...   ...  ..    ...
5125   19    02   63745               SEI    00560     0    1    04  03      1
5126   19    02   63745        MONASTERIO    00564     0    1    04  03      1
5127   19    02   63745        MONASTERIO    00566     0    1    04  03      1
5128   19    02   63760             RAUCH        0     0    1    03  03      1
5129   19    02   63760           LACROZE    00023     0    1    03  03      1
5130   19    02   63760                 A    00025     0    1    03  03      1
5131   19    02   63760               RAC    00032     0    1    03  03      1
5132   19    02   63760             RAUCH    00033     0    1    03  03      1
5133   19    02   63760           LACROZE    00059     0    1    03  03      1
5134   19    02   63760           LACROZE    00093     0    1    03  03      1
5135   19    02   63760              FEDE    00103    00    1    03  03      1
5136   19    02   63760                AH    00107     0    1    03  03      1
5137   19    02   63760               AWC    00118     0    1    03  03      1
5138   19    02   63760                AH    00129     0    1    03  03      1
5139   19    02   63760             RAUCH    00132    00    1    03  03      1
5140   19    02   63760                RW    00137     0    1    03  03      1
5141   19    02   63760             RAUCH    00142     0    1    03  03      1
5142   19    02   63760             BAUCH    00147     0    1    03  03      1
5143   19    02   63760                 W    00147     0    1    03  03      1
5144   19    02   63760                 A    00150     0    1    03  03      1
5145   19    02   63760             E0 AC    00151     0    1    03  03      1
5146   19    02   63760             RAUCH    00152     0    1    03  03      1
5147   19    02   63760                 A    00155     0    1    03  03      1
5148   19    02   63760                AH    00157     0    1    03  03      1
5149   19    02   63760                RA    00159     0    1    03  03      1
5150   19    02   63760  FEDERICO LACROZE    00160     0    1    03  03      1
5151   19    02   63760             RAUCH    00168     0    1    03  03      1
5152   19    02   63760                AE    00180     0    1    03  03      1
5153   19    02   63760           FE LCZE      133     0    1    03  03      1
5154   19    02   63785        RIO PARANA    00039     0    1  None  03      1

[5155 rows x 10 columns]
Operation done successfully

In [211]:
import psycopg2
import pandas as pd

conn = psycopg2.connect(database = "halpe", user = "halpe", password = "halpe", host = "172.26.67.239", port = "5432")
print "Opened database successfully"
cur = conn.cursor()

sql = ("select mza::integer, v_mza::integer "
        "from segmenta.pilar_mzas_adjacentes "
        "where frac='07' and radio='01'"  #vamos a trabajar con este ejemplo
        "order by mza, v_mza;"
      )
cur.execute(sql)
colnames = [desc[0] for desc in cur.description]
adyacencias_x_manzanas = pd.DataFrame(cur.fetchall(), columns = colnames)

print(adyacencias_x_manzanas)

sql = ("select mza, sum(viviendas) as viviendas "
       "from segmenta.pilar_vivs_x_lado "
       "where (frac, radio, mza) in (select frac, radio, mza::integer from segmenta.pilar_mzas_adjacentes) "
       "and frac='07' and radio='01'"
       "group by mza "
       "order by mza;"
      )
cur.execute(sql)
colnames = [desc[0] for desc in cur.description]
viviendas_x_manzanas = pd.DataFrame(cur.fetchall(), columns = colnames)

print(viviendas_x_manzanas)


print "Operation done successfully";
conn.close()

Opened database successfully
     mza  v_mza
0      1      2
1      2      1
2      2      3
3      2      5
4      3      2
5      3      4
6      3      8
7      4      3
8      4      5
9      4      7
10     5      2
11     5      4
12     5      6
13     5      7
14     5     11
15     5     12
16     6      5
17     6      7
18     6     11
19     7      4
20     7      5
21     7      6
22     7      8
23     7     10
24     8      3
25     8      7
26     8      9
27     9      8
28     9     10
29     9     15
..   ...    ...
84    22     21
85    22     23
86    22     26
87    22     27
88    23     17
89    23     22
90    23     24
91    23     25
92    24     17
93    24     23
94    25     23
95    25     26
96    25    970
97    26     22
98    26     25
99    26     27
100   26    970
101   27     22
102   27     26
103   27     28
104   27    970
105   28     21
106   28     27
107   28    970
108  970     12
109  970     21
110  970     25
111  970     26
112  970     27
113  970     28

[114 rows x 2 columns]
    mza viviendas
0     1         2
1     2         9
2     3        13
3     4        12
4     5        96
5     7         6
6     8        22
7     9         6
8    10        17
9    11        22
10   12        60
11   13         8
12   15        13
13   17        16
14   18         1
15   19         1
16   20        11
17   21        28
18   22        10
19   23        17
20   25        17
21   26         9
22   27         4
23  970         7
Operation done successfully

In [205]:
# algortimo a manzanas

cantidad_de_viviendas_deseada = 36

def penalidad_de_bloque(bloque):
    return (sum(bloque) - cantidad_de_viviendas_deseada)**2
def costo_segmentacion(segmentacion):
    return sum(map(penalidad_de_bloque, segmentacion))


print(penalidad_de_bloque([36])) 
print(penalidad_de_bloque([0]))
print(penalidad_de_bloque([0, 0,]))
print(penalidad_de_bloque([0, 0, 36]))

print(costo_segmentacion([[36], [36]]))
print(costo_segmentacion([[36], [0]]))
print(costo_segmentacion([[35], [37]]))
print(costo_segmentacion([[34], [38]]))

0
1296
1296
0
0
1296
2
8

In [229]:
mzas = pd.merge(viviendas_x_manzanas, adyacencias_x_manzanas, on= ['mza'], how = 'right', sort = True).fillna(0)
mzas_gr = mzas.groupby(['mza', 'viviendas'])['v_mza'].apply(list).reset_index()

manzanas = mzas_gr.set_index(['mza']).to_dict()

print(manzanas['v_mza'])
for mza, adyacentes in enumerate(manzanas['v_mza']):
    print(adyacentes)
for mza, viviendas in enumerate(manzanas['viviendas']):
    print mza, viviendas

{1: [2], 2: [1, 3, 5], 3: [2, 4, 8], 4: [3, 5, 7], 5: [2, 4, 6, 7, 11, 12], 6: [5, 7, 11], 7: [4, 5, 6, 8, 10], 8: [3, 7, 9], 9: [8, 10, 15], 10: [7, 9, 11, 14], 11: [5, 6, 10, 12, 13], 12: [5, 11, 13, 20, 21, 970], 13: [11, 12, 14, 19, 20], 14: [10, 13, 15, 18], 15: [9, 14, 16, 17], 16: [15, 17], 17: [15, 16, 18, 23, 24], 18: [14, 17, 19, 22], 19: [13, 18, 20, 21], 20: [12, 13, 19, 21], 21: [12, 19, 20, 22, 28, 970], 22: [18, 21, 23, 26, 27], 23: [17, 22, 24, 25], 24: [17, 23], 25: [23, 26, 970], 26: [22, 25, 27, 970], 27: [22, 26, 28, 970], 28: [21, 27, 970], 970: [12, 21, 25, 26, 27, 28]}

TypeError: 'numpy.int64' object is not iterable

In [209]:
viv_list = mzas_gr.groupby(['frac', 'radio'])['viviendas'].apply(list)
mzas_list = mzas_gr.groupby(['frac', 'radio'])['mza'].apply(list)

print(mzas_list['07']['01'])

radio = viv_list['07']['01']
#print(radio)

una_manzana_un_bloque = []
for mza in radio:
    una_manzana_un_bloque.append([mza])
#print(una_manzana_un_bloque)
print(costo_segmentacion(una_manzana_un_bloque))
print(costo_segmentacion([radio]))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 970]
25043
137641